### ISSUE TITLE
feedback 3

### ISSUE THREAD

**Issue by PatNei** [ITU-BDSA23-GROUP7/Chirp#87]
# Group 7 
er her ikke: dafi

Still using sqlite database right?

kan brugere følge hinanden? <- ikke endnu

I bruger dto's til cheeps men ikke til authors, medmindre det er det som authorInfo (bør renames så) er
	- I bør nok også rykke dem ud i deres egen seperate fil, bare for at gøre det mere overskueligt for helge at se at i bruger dem.

1 warning når man builder
	- Inden i aflevere projektet bør det kunne buildes uden warnings

God test suite, 
 - til integration testing kan man blive inspireret af de der grønne og røde bokse som helge har lavet til jer :)
 
Man kan ikke tilføje cheeps right?
 - Den console logger, det skal bare være færdigt inden projekt aflevering. (en af de vigtigste elementer ved twitter)

jeg kan se i har noget restriction ift. max length på cheep er lig 160 chars
	- dette er helt korrekt ift. opgaven men kan se at det er en restriction i front enden. 
	- i bør også gøre det i backend, tror faktisk bare det er en data annotation til jeres model i efcore. [dotnet documentation for data annotations](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations)
```csharp
public class cheep(){
[MaxLength(160, ErrorMessage = "hello")] // Defined minimum length is not required
public string text;
}
```
	

Login
	- Virker, helge har skrevet til os at det skal være uden ekstra credintials, som den der verifications kode som man skal indtaste
	I bør fikse dette, da det dræber helges script.

**Comment by SDeLaVida** [comment]
I kan altid lige skrive, hvis der var noget vi ikke fik talt om :)

**Comment by SDeLaVida** [comment]
- skal client id være secret, altså må den gerne være oppe på github. (Gruppe 7) <- ikke et problem umiddelbart.

**Comment by SDeLaVida** [comment]
Der skal ikke være noget email verifikation når man logger ind.
	- Azure b2c der kan man få en knap hvor man kan skippe hele email og kode verifikations delen
