### ISSUE TITLE
IEnumerable to list, brug en icollection i stedet :)

### ISSUE THREAD

**Issue by PatNei** [ITU-BDSA23-GROUP7/Chirp#90]
IEnumerable to list, brug en icollection i stedet :)

https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1?view=net-8.0

**Comment by SDeLaVida** [comment]
![image](https://github.com/ITU-BDSA23-GROUP7/Chirp/assets/49490990/5ac9cd13-dc54-4aa1-9bab-c5c12921f5e0)
